// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("grafana");

/**
 * Credentials for accessing the Grafana API.
 */
export let auth: string | undefined = __config.get("auth");
/**
 * URL of the root of the target Grafana server.
 */
export let url: string | undefined = __config.get("url");
