# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "access_mode": "accessMode",
    "admin_user": "adminUser",
    "basic_auth_enabled": "basicAuthEnabled",
    "basic_auth_password": "basicAuthPassword",
    "basic_auth_username": "basicAuthUsername",
    "config_json": "configJson",
    "create_users": "createUsers",
    "database_name": "databaseName",
    "is_default": "isDefault",
    "json_data": "jsonData",
    "org_id": "orgId",
    "secure_json_datas": "secureJsonDatas",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "accessMode": "access_mode",
    "adminUser": "admin_user",
    "basicAuthEnabled": "basic_auth_enabled",
    "basicAuthPassword": "basic_auth_password",
    "basicAuthUsername": "basic_auth_username",
    "configJson": "config_json",
    "createUsers": "create_users",
    "databaseName": "database_name",
    "isDefault": "is_default",
    "jsonData": "json_data",
    "orgId": "org_id",
    "secureJsonDatas": "secure_json_datas",
}
