// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";

export interface DataSourceSecureJsonData {
    accessKey: pulumi.Input<string>;
    secretKey: pulumi.Input<string>;
}
