// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AlertNotification extends pulumi.CustomResource {
    /**
     * Get an existing AlertNotification resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertNotificationState, opts?: pulumi.CustomResourceOptions): AlertNotification {
        return new AlertNotification(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'grafana:index/alertNotification:AlertNotification';

    /**
     * Returns true if the given object is an instance of AlertNotification.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlertNotification {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlertNotification.__pulumiType;
    }

    public readonly isDefault!: pulumi.Output<boolean | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly settings!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a AlertNotification resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertNotificationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertNotificationArgs | AlertNotificationState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as AlertNotificationState | undefined;
            inputs["isDefault"] = state ? state.isDefault : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["settings"] = state ? state.settings : undefined;
            inputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as AlertNotificationArgs | undefined;
            if (!args || args.type === undefined) {
                throw new Error("Missing required property 'type'");
            }
            inputs["isDefault"] = args ? args.isDefault : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["settings"] = args ? args.settings : undefined;
            inputs["type"] = args ? args.type : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(AlertNotification.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AlertNotification resources.
 */
export interface AlertNotificationState {
    readonly isDefault?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly settings?: pulumi.Input<{[key: string]: any}>;
    readonly type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AlertNotification resource.
 */
export interface AlertNotificationArgs {
    readonly isDefault?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly settings?: pulumi.Input<{[key: string]: any}>;
    readonly type: pulumi.Input<string>;
}
