// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class DataSource extends pulumi.CustomResource {
    /**
     * Get an existing DataSource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DataSourceState, opts?: pulumi.CustomResourceOptions): DataSource {
        return new DataSource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'grafana:index/dataSource:DataSource';

    /**
     * Returns true if the given object is an instance of DataSource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DataSource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DataSource.__pulumiType;
    }

    public readonly accessMode!: pulumi.Output<string | undefined>;
    public readonly basicAuthEnabled!: pulumi.Output<boolean | undefined>;
    public readonly basicAuthPassword!: pulumi.Output<string | undefined>;
    public readonly basicAuthUsername!: pulumi.Output<string | undefined>;
    public readonly databaseName!: pulumi.Output<string | undefined>;
    public readonly isDefault!: pulumi.Output<boolean | undefined>;
    public readonly jsonData!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly password!: pulumi.Output<string | undefined>;
    public readonly secureJsonDatas!: pulumi.Output<outputs.DataSourceSecureJsonData[] | undefined>;
    public readonly type!: pulumi.Output<string>;
    public readonly url!: pulumi.Output<string | undefined>;
    public readonly username!: pulumi.Output<string | undefined>;

    /**
     * Create a DataSource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DataSourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DataSourceArgs | DataSourceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as DataSourceState | undefined;
            inputs["accessMode"] = state ? state.accessMode : undefined;
            inputs["basicAuthEnabled"] = state ? state.basicAuthEnabled : undefined;
            inputs["basicAuthPassword"] = state ? state.basicAuthPassword : undefined;
            inputs["basicAuthUsername"] = state ? state.basicAuthUsername : undefined;
            inputs["databaseName"] = state ? state.databaseName : undefined;
            inputs["isDefault"] = state ? state.isDefault : undefined;
            inputs["jsonData"] = state ? state.jsonData : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["password"] = state ? state.password : undefined;
            inputs["secureJsonDatas"] = state ? state.secureJsonDatas : undefined;
            inputs["type"] = state ? state.type : undefined;
            inputs["url"] = state ? state.url : undefined;
            inputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as DataSourceArgs | undefined;
            if (!args || args.type === undefined) {
                throw new Error("Missing required property 'type'");
            }
            inputs["accessMode"] = args ? args.accessMode : undefined;
            inputs["basicAuthEnabled"] = args ? args.basicAuthEnabled : undefined;
            inputs["basicAuthPassword"] = args ? args.basicAuthPassword : undefined;
            inputs["basicAuthUsername"] = args ? args.basicAuthUsername : undefined;
            inputs["databaseName"] = args ? args.databaseName : undefined;
            inputs["isDefault"] = args ? args.isDefault : undefined;
            inputs["jsonData"] = args ? args.jsonData : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["password"] = args ? args.password : undefined;
            inputs["secureJsonDatas"] = args ? args.secureJsonDatas : undefined;
            inputs["type"] = args ? args.type : undefined;
            inputs["url"] = args ? args.url : undefined;
            inputs["username"] = args ? args.username : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(DataSource.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DataSource resources.
 */
export interface DataSourceState {
    readonly accessMode?: pulumi.Input<string>;
    readonly basicAuthEnabled?: pulumi.Input<boolean>;
    readonly basicAuthPassword?: pulumi.Input<string>;
    readonly basicAuthUsername?: pulumi.Input<string>;
    readonly databaseName?: pulumi.Input<string>;
    readonly isDefault?: pulumi.Input<boolean>;
    readonly jsonData?: pulumi.Input<{[key: string]: any}>;
    readonly name?: pulumi.Input<string>;
    readonly password?: pulumi.Input<string>;
    readonly secureJsonDatas?: pulumi.Input<pulumi.Input<inputs.DataSourceSecureJsonData>[]>;
    readonly type?: pulumi.Input<string>;
    readonly url?: pulumi.Input<string>;
    readonly username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DataSource resource.
 */
export interface DataSourceArgs {
    readonly accessMode?: pulumi.Input<string>;
    readonly basicAuthEnabled?: pulumi.Input<boolean>;
    readonly basicAuthPassword?: pulumi.Input<string>;
    readonly basicAuthUsername?: pulumi.Input<string>;
    readonly databaseName?: pulumi.Input<string>;
    readonly isDefault?: pulumi.Input<boolean>;
    readonly jsonData?: pulumi.Input<{[key: string]: any}>;
    readonly name?: pulumi.Input<string>;
    readonly password?: pulumi.Input<string>;
    readonly secureJsonDatas?: pulumi.Input<pulumi.Input<inputs.DataSourceSecureJsonData>[]>;
    readonly type: pulumi.Input<string>;
    readonly url?: pulumi.Input<string>;
    readonly username?: pulumi.Input<string>;
}
